# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://satoshi-ninja.github.io/spmt/"
languageCode = "en-US"
title = "Secure Pivx Masternode Tool"
publishDir = "docs"

# Metadata
[params]
  author = "Satoshi Ninja"
  description = "Secure Pivx Masternode Tool: activate your Pivx masternode with your hardware wallet."

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "<img src='https://satoshi-ninja.github.io/spmt/images/spmt-logo.png'/>Secure Pivx Masternode Tool"
  description = "The fun and the convenience of Pivx, <br> the security of your hardware wallet."

# Navigation section
[params.nav]
  mission = "About"
  services = "Download"
  # team = "The Team"
  # contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Masternodes"
    subtitle = "Pivx Masternodes are full-nodes incentivized by a share of the block reward for the work they do for the Pivx network."
    description = "<p>To run a masternode, apart from setting up a server wich runs the Pivx software, one must tie up a 10000 Pivx collateral to the node.<br/> The private key controlling the address with the 10000 Pivx can be kept on a different Pivx node, outside of the masternode server itself, for security reasons. However, before the rest of the PIVX network can accept the masternode as legitimate, the owner of the Pivx masternode must prove he/she is also in control of the private key holding the collateral. This is achieved by sending to the Pivx network a special 'start masternode' message signed by this private key corresponding to the address with the collateral.</p>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "The Problem"
    subtitle = "Pivx masternode owners risk exposing the private keys of their collaterals every time they start a masternode."
    description = "<p>Signing the 'start masternode' message can be only performed within the <a href='https://pivx.org/wallet/'>Pivx Core wallet</a> from an hot address, a Pivx address which is has been directly exposed online.<br/>The recent increase in the value of Pivx (10000 Pivx = ca. 30k$ at the moment of writing) has increased the risk of keeping masternode collaterals on hot addresses.</p>"

  [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "The Solution"
    subtitle = "The Secure Pivix Masternode Tool gives Pivx masternode owners the ability to start masternodes without ever exposing your private keys."
    description = "<p>The recent implementation of Pivx derivations into the Ledger Nano S hardware wallet makes it now possible to offer the Pivx community a tool similar to the <a href='https://github.com/Bertrand256/dash-masternode-tool'>DASH Masternode Tool</a> a tool which allows Dash owners to sign the 'start masternode' message with the private key of a collateral kept on a secure element of an hardware wallet. Hardware wallets contain private keys which are never exposed online.<br/>The Secure Pivix Masternode Tool gives the owners of Pivx masternode the ability to send a 'start masternode' command via an easy to use a graphical interface using a collateral that is controlled by an hardware wallet such as Ledger Nano S, an hardware wallet with secure element containing private keys which are never exposed online.</p>"

# Services section
[params.services]
  enable = true
  video = true
  vidlink = "https://www.youtube.com/embed/KAmAX6ZVziI"
  title = "Live Demo"
  description = "The Secure Pivix Masternode Tool is very easy to use.</p>"

  [[params.services.item]]
    icon = "icon-gears"
    title = "Multi-OS"
    description = "The Python back-end and the QT front-end allow the SPMT to be easily ported across different OS."

  [[params.services.item]]
    icon = "icon-plug"
    title = "RPC Independent"
    description = "Whether you want to use a local or a remote server, SPMT is designed to be RPC server independent."

  [[params.services.item]]
    icon = "icon-unlock2"
    title = "HW Independent"
    description = "SPMT is designed to be Hardware Wallet independent; Ledger Wallet is at the moment fully supported."

  [[params.services.item]]
    icon = "icon-heartbeat"
    title = "Connectivity Watchdog"
    description = "SPMT implements a convenient Connectivity Watchdog for the connection to the RPC server."

  [[params.services.item]]
    icon = "icon-pied-piper"
    title = "In-App Reward Management"
    description = "SPMT implements an In-App Reward Management panel, to safely transfer masternode earnings."

  [[params.services.item]]
    icon = "icon-terminal"
    title = "Debug Console"
    description = "SPMT integrates a state of the art console with toggable debug and log management functions."

[[params.services.item]]
    icon = "icon-server2"
    title = "Masternode Management"
    description = "SPMT facilitates the management of multiple masternodes at once, as well as the creation of new ones."

    [[params.services.item]]
    icon = "icon-tachometer"
    title = "Masternode Monitoring"
    description = "SPMT allows monitoring several aspects of the masternodes status such as networking & ranking info."

    [[params.services.item]]
    icon = "icon-github"
    title = "Open Source"
    description = "SPMT is 100% free software. If you want to contribute to the source code you can fork us on GitHub!"

# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = false
  title = "Meet The Team"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.team.item]]
    name = "Jean Doe"
    position = "Chief legend"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person1.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"
    linkedin = "#"

  [[params.team.item]]
    name = "Alice Doe"
    position = "Chief overlord"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person2.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  [[params.team.item]]
    name = "John Doe"
    position = "Chief haranguer"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person3.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = false
  title = "Get In Touch"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  github = "#"
  # twitter = "#"
  # facebook = "#"
  # vine = "#"
  # linkedin = "#"
  # instagram = "#"
  
